name: 'CI-CD Docker'

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Chekout
        uses: actions/checkout@v3
      -
        name: Set up Docker Bildx 
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      -
        name: Build and push image
        uses: docker/build-push-action@v4
        with:
          repository: tipaproger/ci-cd_httpd_github_actions
          push: true
          tags: latest, ${{ github.run_number }}